image: Visual Studio 2017

version: 6.0.2.{build}

branches:
  only:
    - master

skip_commits:
  message: /updated? readme.*s/

build: false

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      Install-Module InvokeBuild, Indented.Build
      Set-Location $env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME
  - pwsh: |
      Set-Location $env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME
      Install-Module InvokeBuild, Indented.Build

build_script:
  - ps: Start-Build -BuildType Setup, Build
  - pwsh: Start-Build -BuildType Setup, Build

test_script:
  - ps: Start-Build -BuildType Setup, Test
  - pwsh: Start-Build -BuildType Setup, Test
